runtime: nodejs18
env: standard

# Region configuration
region: europe-west1

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  NODE_ENV: production
  PORT: 8080

handlers:
  - url: /api/.*
    script: auto
  - url: /.*
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /static/.*
    static_dir: client/build/static
