steps:
  # Build Docker image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/cv-rank-generator',
      '--cache-from', 'gcr.io/$PROJECT_ID/cv-rank-generator:latest',
      '.'
    ]

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cv-rank-generator']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'cv-rank-generator',
      '--image', 'gcr.io/$PROJECT_ID/cv-rank-generator',
      '--platform', 'managed',
      '--region', 'europe-west1',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '2',
      '--max-instances', '10'
    ]

# Build options for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
